# Generated by Django 4.2.4 on 2023-08-19 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '__first__'),
        ('publicaciones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_visualizacion', models.CharField(choices=[('autor', 'Autor'), ('editor', 'Editor'), ('publicador', 'Publicador')], max_length=20)),
                ('publicaciones', models.ManyToManyField(to='publicaciones.publicacion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rol')),
            ],
        ),
    ]
