# Generated by Django 4.2.4 on 2023-08-19 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rich_text', 'Rich Text'), ('solo_text', 'Solo Text')], max_length=10)),
                ('resumen', models.TextField()),
                ('id_publicacion', models.CharField(max_length=20)),
                ('share', models.BooleanField(default=False)),
                ('codigo_qr', models.ImageField(blank=True, upload_to='codigos_qr/')),
                ('imagen_thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'Revisión'), ('publicar', 'Publicar'), ('publicado', 'Publicado'), ('rechazado', 'Rechazado'), ('inactivo', 'Inactivo')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('programar_publicacion', models.DateTimeField(blank=True, null=True)),
                ('vigencia_publicacion', models.DateTimeField(blank=True, null=True)),
                ('suscriptores_exclusivos', models.BooleanField(default=False)),
                ('palabras_clave', models.CharField(blank=True, max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='publicaciones_disliked', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='publicaciones_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
